---
title: "VR-Eye on the RAPID Dataset"
author: "Claire Cross, Cass Mayeda"
date: "2024-05-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# # uncomment lines below to install packages
# if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("Biobase")
# BiocManager::install("flowCore")
# install.packages("ggplot2", repos = "http://cran.us.r-project.org")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# install.packages("cowplot", repos = "http://cran.us.r-project.org")
# install.packages("RColorBrewer", repos = "http://cran.us.r-project.org")
# #install.packages("viridis", repos = "http://cran.us.r-project.org")
# #install.packages("data.table", repos = "http://cran.us.r-project.org")
# install.packages("stringr", repos = "http://cran.us.r-project.org")
# install.packages("FNN", repos = "http://cran.us.r-project.org")
# #install.packages("matrixStats", repos = "http://cran.us.r-project.org")
# BiocManager::install("cytoMEM")
# # install.packages("gplots", repos = "http://cran.us.r-project.org")
# # install.packages("gbutils", repos = "http://cran.us.r-project.org")
# install.packages("dbscan", repos = "http://cran.us.r-project.org")
# install.packages("scales", repos = "http://cran.us.r-project.org")
```

```{r initialization}
#load packages into the working library
suppressPackageStartupMessages({library(Biobase)
                                library(flowCore)
                                library(ggplot2)
                                library(tidyverse)
                                library(cowplot)
                                library(RColorBrewer)
                                #library(viridis)
                                #library(data.table)
                                library(stringr)
                                library(FNN)
                                #library(matrixStats)
                                library(cytoMEM)
                                #library(gplots)
                                #library(gbutils)
                                library(dbscan)
                                library(scales)})
source("./R/tSNE_plots.R")
source("./R/VR-Eye_functions.R")
source("./R/VR-Eye_plots.R")
source('./R/tatarize_color_palette.R')
expr.colors = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(5)

#specify fcs file location and output path
file.path <- './data files/RAPID - Leelatian and Sinnaeve et al/'
og.output.path <- './output files/VR-Eye_RAPID/'

#locate fcs file
fcs.files <- dir(path = file.path, pattern = "*.fcs")
print(fcs.files)

#do you wish to downsample the data?
sample.files <- FALSE
sample.num <- 1000 
```

```{r load data}
#load cell data
setwd(file.path)
data.list <- lapply(lapply(fcs.files, read.FCS, truncate_max_range = FALSE), exprs)
combined.patient.data <- as.data.frame(do.call(rbind, mapply(cbind, data.list, "File_ID"= c(1:length(data.list)), SIMPLIFY=F)))
colnames(combined.patient.data)[1:(ncol(combined.patient.data)-1)] <- as.character(read.FCS(fcs.files[1], truncate_max_range=FALSE)@parameters@data[["desc"]])
colnames(combined.patient.data)

#get sample names
sample.group <- "RAPID"
sample.levels <- c()
split.names <- lapply(fcs.files, function(x) str_split(x, '_')[[1]][1]) #split file names by _
split.names <- lapply(split.names, function(x) str_split(x, ' ')[[1]]) # split names by space
#trim date from names
for(i in 1:length(split.names)){
  if(length(split.names[[i]]) > 1){
    sample.levels <- c(sample.levels, split.names[[i]][2]) #ignore data
  }else{sample.levels <- c(sample.levels, split.names[[i]][1])}
}
```

```{r downsampling}
if (sample.files == TRUE){ 
  #set seed for reproducibility
  set.seed(1)
  #split into individual files
  files.to.sample <- split(combined.patient.data, combined.patient.data$`File_ID`) 
  sampled.data <- list()
  for (i in 1:length(files.to.sample)){
    #file has a lot of cells => we must downsample
    if ((nrow(files.to.sample[[i]])) >= sample.num){ 
      sampled.data[[i]] <- as.data.frame(files.to.sample[[i]][sample(nrow(files.to.sample[[i]]), sample.num), ])
    #not enough cells to downsample => just keep all of the cells present
    }else{sampled.data[[i]] <- files.to.sample[[i]]}
  }
  #combine list data into one big data frame
  combined.sampled.data <- as.data.frame(do.call(rbind, sampled.data))
}else{combined.sampled.data <- combined.patient.data}

print(paste0(nrow(combined.sampled.data), ' cells will be analyzed'))
```

```{r select data}
#select tSNE columns 
tSNE.indx1 <- 46
tSNE.indx2 <- 47
tSNE.data <- combined.sampled.data[, c(tSNE.indx1:tSNE.indx2)]
colnames(tSNE.data) <- c("tSNE1", "tSNE2")

#select marker channels
panel.info <- marker.selection(colnames(combined.patient.data), token='-', position='before')
panel.info[1,'trimmed_names'] <- 'CyclinB1' #correct typo
panel.info[2,'trimmed_names'] <- 'B3TUB' #rename TUJ1 marker
print(panel.info$trimmed_names)
marker.data <- combined.sampled.data[, panel.info$indices]

#arcsinh transformation
cofactor <- 5
marker.data <- asinh(marker.data/cofactor)
colnames(marker.data) <- panel.info$trimmed_names
```

```{r t-SNE plots}
#plot tSNE axes
tsne.plot <- ggplot(tSNE.data) + geom_point(aes(x=tSNE2, y=tSNE1), color='lightgrey') +
              labs(x='t-SNE2', y='t-SNE1', title='RAPID GBM Cohort', 
                   caption="Data from Leelatian & Sinnaeve et al., eLife. 2020") + 
              coord_fixed(ratio=1) + theme_bw() + theme(panel.grid = element_blank())
print(tsne.plot)

#plot cell density on t-SNE axes
tsne.dens.plot <- tsne_density(tSNE.data, export=TRUE, output_path=og.output.path)

#plot heat on markers
tsne.heat.on.markers <- tsne_heat_on_markers(tSNE.data, marker.data, n_col=8, export=TRUE, output_path=og.output.path)
```

```{r, set VR constants}
#KNN settings
kvalue <- 60

#set minimum cluster size
min.cluster <- 15

#DBSCAN settings
db.eps <- 2 
```

```{r KNN MEM}
#look for existing KNN labels file
knn.path <- og.output.path
setwd(knn.path)
knn.data.file <- dir(pattern='knn labels.RData')
rds.name <- paste0(knn.path, 'knn labels.RData')
  
#load knn.labels if the file exists; otherwise, calculate knn.labels
if(is.na(knn.data.file[1])){
  start_time = Sys.time()
  knn.labels = knn_MEM(tSNE.data, marker.data, kvalue=kvalue)
  total_time = Sys.time() - start_time
  print(' KNN MEM completed in ')
  print(total_time)
    
  #save as rds 
  save(knn.labels, file = paste0(og.output.path, 'knn labels.RData'))
}else{load(file=rds.name)}
```

```{r set VR searching info}
#specify searching labels and goals
goals <- c('GNP', 'GPP')
ref.labels <- c('SOX2+7 S100B+4 GFAP+1 p-NFkB+0', #optimized GNP reference label 
                'EGFR+7 CD49F+2 pp38+2 CD44+1 B3TUB+0') #optimized GPP reference label
```

```{r, VR-Eye}
#set multi-round variables
current_round <- 0 
multi.labels <- data.frame()
multi.df <- combined.sampled.data

#search for each ref label supplied
for (j in 1:length(goals)){
  #get goal & search label
  goal <- goals[j]
  ref.label <- ref.labels[j]
  print(paste0('searching for ', goal, ': ', ref.label))

  # check that markers in the searching label are being measured in the new dataset
  common.label <- check_panel(ref.label, panel.info)
  common.ref.MEM.score <- common.label[[1]]
  ref.label <- common.label[[2]]

  # create output folder
  current_round <- current_round + 1
  run.folder <- paste0(og.output.path, goal, '/')
  dir.create(run.folder)

  #VR-Eye search and sim plot
  common.MEM.scores <- knn.labels[, colnames(common.ref.MEM.score)]

  #check if only one marker
  if (!is.data.frame(common.MEM.scores)) {
    common.MEM.scores <- as.data.frame(common.MEM.scores)
    colnames(common.MEM.scores) <- colnames(common.ref.MEM.score)
  }
    
  #calculate similarity
  print('calculating similarity')
  sim <- sim_scores(common.MEM.scores, common.ref.MEM.score)
  my.range <- max(sim)-min(sim)
  sim.data <- cbind(marker.data, File_ID = i, tSNE.data, sim)
  sim.plot <- VR_Eye_sim_plot(sim.data, ref.label)
  #export
  png(paste0(run.folder, goal, " similarity.png"),
      height = 1500, width = 1500, res = 200)
  print(sim.plot)
  dev.off()

  #save round information to multi.df
  print('saving data to multi.df')
  this.round <- c()
  this.round = cbind(
    VRPTR_round = current_round,
    search_label = ref.label,
    goal = goal,
    min.clust = min.cluster,
    kvalue = kvalue
  )
  multi.labels <- rbind(multi.labels, this.round)
  save(multi.labels, file = paste0(og.output.path, "multi-run labels.RData"))

  #save similarity score in multi-round results df
  multi.df <- cbind(multi.df, sim)
  colnames(multi.df)[ncol(multi.df)] <- paste0("r", current_round, "_sim")

  #update multi.df
  rds.name <- paste0(og.output.path, 'multi-run VRPTR.RData')
  save(multi.df, file = rds.name)
}
```

```{r similarity binning}

```

```{r plot population abundance per patient}

```

```{r plot similarity axis per patient}

```








```{r export as fcs}
#split data by patient
separate.fcs.files <- split(all.IEI.Eye.data[,c(1:88)], all.IEI.Eye.data$File_ID)
for (i in 1:length(separate.fcs.files)){
  #format data
  single.file <- separate.fcs.files[[i]]
  reduce.data <- single.file[,c(1:87)]
  mat.input <- as.matrix(reduce.data)
  #set metadata
  metadata <- data.frame(name=dimnames(mat.input)[[2]], desc=colnames(all.IEI.Eye.data[,c(1:87)]))
  metadata$range <- apply(apply(mat.input, 2, range), 2, diff)
  metadata$minRange <- apply(mat.input, 2, min)
  metadata$maxRange <- apply(mat.input, 2, max)
  input.flowframe <- new("flowFrame", exprs=mat.input,parameters = AnnotatedDataFrame(metadata))  
  newname <- single.file[1,'Patient_ID']
  new.filename <- paste0(og.output.path, '/', strftime(Sys.time(),"%Y-%m-%d"), "_", newname, "_VR-Eye.fcs")
  write.FCS(input.flowframe, filename=new.filename)
  print(paste0("FCS file ", i, ': ', single.file[1,'Patient_ID'],  " done"))
}
```
